config/routes.rb
Rails.application.routes.draw do
  resources :tweets do
    post 'likes', to:'tweets#likes'
    post 'retweet', to:'tweets#retweet'
  end

  get 'home/index'
  
  devise_for :users

  root to: 'home#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :tweet
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  validates :content, presence:true

  belongs_to :user
  has_many :likes
  has_many :liking_users, through: :likes, source: :user

  

  paginates_per 50

  def is_liked?(user)
    if self.liking_users.include?(user)
      true
    else
      false
    end
  end

  def add_like(user)
    Like.create(user: user, tweet: self)  
  end

  def remove_like(user)
    Like.where(user: user, tweet: self).first.destroy
  end

  def like_icon(user)
    if is_liked?(user)
      'fas fa-heart'
    else
      'far fa-heart'
    end
  end

  def count_rt
    Tweet.where(rt_ref: self.id).count
  end

  def is_retweet?
    rt_ref ? true : false
  end

  def tweet_ref
    Tweet.find(self.rt_ref)
  end

  # def retweet_icon
  #   if self.count_rt > 0
  #     "text-warning"
  #   else
  #     "text-muted"
  #   end
  # end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :tweets
  has_many :likes

  has_many :liked_tweets, through: :likes, source: :tweet
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/view.rb
class View < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

    before_action :configure_permited_parameters, if: :devise_controller?

    protected
    def configure_permited_parameters
        devise_parameter_sanitizer.permit(:sign_up, keys:[:username, :photo_url])
    end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    #@tweets = Tweet.all
    @tweets = Tweet.order(created_at: :desc).page params[:page]
    @tweet = Tweet.new
  end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :set_tweet, only: [:show, :edit, :update, :destroy]
  before_action :set_current_tweet, only:[:likes, :retweet]

  # GET /tweets
  # GET /tweets.json
  def index
    @tweets = Tweet.all
  end

  # GET /tweets/1
  # GET /tweets/1.json
  def show
  end

  # GET /tweets/new
  def new
    @tweet = Tweet.new
  end

  # GET /tweets/1/edit
  def edit
  end

  # POST /tweets
  # POST /tweets.json
  def create
    @tweet = Tweet.new(tweet_params)
    @tweet.user = current_user


    respond_to do |format|
      if @tweet.save
        #format.html { redirect_to @tweet, notice: 'Tweet was successfully created.' }
        format.html { redirect_to root_path, notice: 'Tweet was successfully created.' }
        format.json { render :show, status: :created, location: @tweet }
      else
        format.html { render :new }
        format.json { render json: @tweet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tweets/1
  # PATCH/PUT /tweets/1.json
  def update
    respond_to do |format|
      if @tweet.update(tweet_params)
        format.html { redirect_to @tweet, notice: 'Tweet was successfully updated.' }
        format.json { render :show, status: :ok, location: @tweet }
      else
        format.html { render :edit }
        format.json { render json: @tweet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tweets/1
  # DELETE /tweets/1.json
  def destroy
    @tweet.destroy
    respond_to do |format|
      format.html { redirect_to tweets_url, notice: 'Tweet was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

   def likes
    if @tweet.is_liked?(current_user)
      @tweet.remove_like(current_user)
    else
      @tweet.add_like(current_user)
    end
      redirect_to root_path
   end

   def retweet
      new_tweet = Tweet.create(content: @tweet.content, user: current_user, rt_ref: @tweet.id)
      redirect_to root_path
   end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tweet
      @tweet = Tweet.find(params[:id])
    end

    def set_current_tweet
      @tweet = Tweet.find(params[:tweet_id])
    end

    # Only allow a list of trusted parameters through.
    def tweet_params
      params.require(:tweet).permit(:content, :user_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/views/home/index.html.erb
<div class="container my-4">
    <div class="row">
    <% if user_signed_in?%>
        <div class="col-12">
            <%= render 'tweets/form', tweet: @tweet %>
        </div>
    <%end%>
    <% @tweets.each do |tweet| %>

        <div class="col-12 col-sm-12 col-md-6 col-lg-6 my-5">
            <div class="card mx-1 bg-light">
                
                <div class="container">
                    <div class="row">
                        <div class="col-sm-3 mt-2">
                            <%= image_tag (tweet.user.photo_url), class:"avatar-in-tweet img-fluid rounded-circle" %>
                        </div>

                        <div class="col-sm">
                            <span class="">
                                <%= link_to '<i class="far fa-calendar-alt text-muted"></i>'.html_safe+distance_of_time_in_words(Time.now, tweet.created_at), tweet%>
                            </span>
                            <br/>
                            <span class="username">
                                <%= tweet.user.username%> dice: 
                            </span>
                            <br/>
                        
                            <%= tweet.content %>
                            <%if tweet.is_retweet? %>
                                <%= link_to "Ver original", tweet.tweet_ref%>

                            <%end%>
                        <hr/>
                            <div class="text-center tweet-options">
                                <span>
                                    <%= tweet.likes.count %> 
                                    <%= link_to ('<i class="'+tweet.like_icon(current_user)+' text-warning"></i>').html_safe, tweet_likes_path(tweet), method: :post%>                        
                                </span>
                                    |
                                <span>
                                    <%= tweet.count_rt%>
                                    <%if tweet.count_rt > 0 %> 
                                        <%= link_to '<i class="fas fa-retweet text-warning"></i>'.html_safe, tweet_retweet_path(tweet), method: :post %>
                                    <%else%>
                                        <%= link_to '<i class="fas fa-retweet text-muted"></i>'.html_safe, tweet_retweet_path(tweet), method: :post %>
                                    <%end%>
                                </span>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
            <%end%>

    </div>
</div>

<div class="mt-2">
<%= paginate @tweets%>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%=t('site_title')%></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">

    <script src="https://kit.fontawesome.com/e89d037a76.js" crossorigin="anonymous"></script>
  </head>

  <body style="background-color:#75756b">

    <div class="row">
 
      <div class="col-12">
        <%= render "shared/navbar"%>
       </div>
      <div class="container">
      <% if alert || notice%>
        <div class="alert alert-success mt-3” role="alert >
            <%= notice %>
            <%= alert %>
        </div>
       <%end%>
        
        <%= yield %>
      </div>
    </div>
  <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
  </body>
</html>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container">
    <a class="navbar-brand text-warning" href="<%= root_path%>"><%=t('site_title')%></a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarText">
        <ul class="navbar-nav mr-auto">
        <% if user_signed_in? %>
           <li class="nav-item text-warning">
            <%= link_to 'Cerrar Sesión', destroy_user_session_path, method: :delete, class:'nav-link'%>
          </li> 
        <%else%>
          <li class="nav-item active">
            <%= link_to 'Registro', new_user_registration_path, class:'nav-link text-warning'%>
          </li>
          <li class="nav-item">
            <%= link_to 'Login', new_user_session_path, class:'nav-link text-warning'%>
          </li>
        <%end%>

        </ul>
      </div>
  </div>
</nav>

app/views/tweets/_form.html.erb
<%= form_with(model: tweet, local: true) do |form| %>
  <% if tweet.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(tweet.errors.count, "error") %> prohibited this tweet from being saved:</h2>

      <ul>
        <% tweet.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :content, "#{current_user.username} dice:" %>
    <%= form.text_area :content, id: :tweet_content, class:"form-control" %>
  </div>

  <div class="actions text-center my-2">
    <%= form.submit "Guardar", class:"btn btn-warning" %>
  </div>
<% end %>

app/views/tweets/edit.html.erb
<h1>Editing Tweet</h1>

<%= render 'form', tweet: @tweet %>

<%= link_to 'Show', @tweet %> |
<%= link_to 'Back', tweets_path %>

app/views/tweets/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Tweets</h1>

<table>
  <thead>
    <tr>
      <th>Content</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tweets.each do |tweet| %>
      <tr>
        <td><%= tweet.content %></td>
        <td><%= tweet.user_id %></td>
        <td><%= link_to 'Show', tweet %></td>
        <td><%= link_to 'Edit', edit_tweet_path(tweet) %></td>
        <td><%= link_to 'Destroy', tweet, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Tweet', new_tweet_path %>

app/views/tweets/new.html.erb
<h1>New Tweet</h1>

<%= render 'form', tweet: @tweet %>

<%= link_to 'Back', tweets_path %>

app/views/tweets/show.html.erb
<div class="col-6 col-sm-12 col-md-12 col-lg-12 my-3">
    <div class="card mx-1 bg-light">
        
        <div class="container">
            <div class="row">
                <div class="col-sm-3 mt-2">
                    <%= image_tag (@tweet.user.photo_url), class:"avatar-in-tweet" %>
                </div>
                <div class="col-sm">
                <span class="username">
                    <%= @tweet.user.username%> dice: 
                </span>
            <br/>
                <span class="">
                    <%= link_to '<i class="far fa-calendar-alt"></i>'.html_safe+distance_of_time_in_words(Time.now, @tweet.created_at), @tweet%>
                </span>
            <br/>
            <%= @tweet.content %>
            <%if @tweet.is_retweet?%>
                <%= link_to "Retweet...", @tweet.tweet_ref%>

            <%end%>
        <hr/>
            <div class="text-center tweet-options">
                <span>
                    <%= @tweet.likes.count %> 
                    <%= link_to ('<i class="'+@tweet.like_icon(current_user)+' text-warning"></i>').html_safe, tweet_likes_path(@tweet), method: :post%>                        
                </span>
                    |
                <span>
                    <%= @tweet.count_rt%>
                    <%if @tweet.count_rt > 0 %> 
                        <%= link_to '<i class="fas fa-retweet text-warning"></i>'.html_safe, tweet_retweet_path(@tweet), method: :post %>
                    <%else%>
                        <%= link_to '<i class="fas fa-retweet text-muted"></i>'.html_safe, tweet_retweet_path(@tweet), method: :post %>
                    <%end%>
                </span>
            </div>
        </div>
      </div>
  </div>
</div>

<div>
    <% @tweet.liking_users.each do |user| %>
    <%= image_tag (user.photo_url), class:"avatar-in-tweet rounded" %>
    <%end%>
</div>